docker_build('{{cookiecutter.repo_name}}-tilt', '.', 
    dockerfile='./Dockerfile')
k8s_yaml('../infrastructure/k8s/{{cookiecutter.repo_name}}-deployment.yaml')

k8s_resource('{{cookiecutter.repo_name}}', labels=['{{cookiecutter.repo_name}}'], port_forwards={{cookiecutter.port}})

# appears to fix issues with not being able to communicate with local registry
# https://github.com/docker/for-mac/issues/3611